apiVersion: devops.kubesphere.io/v1alpha1
kind: S2iBuilderTemplate
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
    builder-type.kubesphere.io/s2i: "s2i"
  name: nginx-base
spec:
  containerInfo:
    - builderImage: harbor.wayj.online/tqmobiledev/s2ibuilder-nginx-centos7-base
  codeFramework: nginx # 代码框架类型
  defaultBaseImage: harbor.wayj.online/tqmobiledev/s2ibuilder-nginx-centos7-base # 默认使用的构建器镜像 (可替换为自定义的镜像)
  version: 0.0.1 # 构建器模版的版本
  description: "This is a S2I builder for Nginx builds whose result can be run directly without any further application server.." # 构建器模版的描述信息